# Generated by Django 5.2.10 on 2026-04-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.roomcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Фото категорії',
                'verbose_name_plural': 'Фото категорій',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
                'unique_together': {('country', 'city', 'address')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='bookings.location', verbose_name='Локація'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.room', verbose_name='Кімната')),
            ],
            options={
                'verbose_name': 'Фото кімнати',
                'verbose_name_plural': 'Фото кімнат',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
